const Tags: string[] = [
  "a",
  "abbr",
  "address",
  "area",
  "article",
  "aside",
  "audio",
  "b",
  "base",
  "bdi",
  "bdo",
  "blockquote",
  "body",
  "br",
  "button",
  "canvas",
  "caption",
  "cite",
  "code",
  "col",
  "colgroup",
  "data",
  "datalist",
  "dd",
  "del",
  "details",
  "dfn",
  "dialog",
  "div",
  "dl",
  "dt",
  "em",
  "embed",
  "fieldset",
  "figcaption",
  "figure",
  "footer",
  "form",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "head",
  "header",
  "hr",
  "html",
  "i",
  "iframe",
  "img",
  "input",
  "ins",
  "kbd",
  "label",
  "legend",
  "li",
  "link",
  "main",
  "map",
  "mark",
  "meta",
  "meter",
  "nav",
  "noscript",
  "object",
  "ol",
  "optgroup",
  "option",
  "output",
  "p",
  "param",
  "picture",
  "pre",
  "progress",
  "q",
  "rp",
  "rt",
  "ruby",
  "s",
  "samp",
  "script",
  "section",
  "select",
  "small",
  "source",
  "span",
  "strong",
  "style",
  "sub",
  "summary",
  "sup",
  "table",
  "tbody",
  "td",
  "template",
  "textarea",
  "tfoot",
  "th",
  "thead",
  "time",
  "title",
  "tr",
  "track",
  "u",
  "ul",
  "var",
  "video",
  "wbr",
  "applet",
  "basefont",
  "big",
  "blink",
  "center",
  "command",
  "content",
  "dir",
  "element",
  "font",
  "frame",
  "frameset",
  "image",
  "isindex",
  "keygen",
  "listing",
  "marquee",
  "menu",
  "menuitem",
  "multicol",
  "nextid",
  "nobr",
  "noembed",
  "noframes",
  "plaintext",
  "shadow",
  "spacer",
  "strike",
  "tt",
  "xmp",
  "acronym",
  "bgsound",
  "dir",
  "frameset",
  "noframes",
  "tt",
  "video",
  "audio",
  "button",
  "details",
  "dialog",
  "summary",
  "template",
  "figcaption",
  "mark",
  "wbr",
];
for (let e = 0; e < Tags.length; e++) {
  globalThis[Tags[e]] = (attrs?: { [key: string]: Function }, ...children: (string | number | boolean | null | undefined | HTMLElement)[]) => {
    const el = document.createElement(Tags[e]);
    if (attrs) {
      for (const key in attrs) {
        if (key[0] === "$") {
          el.addEventListener(key.slice(1), attrs[key] as EventListener);
          continue;
        }
        el.setAttribute(key, attrs[key].toString());
      }
    }
    for (let j = 0; j < children.length; j++) {
      if (
        typeof children[j] === "string" ||
        typeof children[j] === "number" ||
        typeof children[j] === "boolean" ||
        children[j] === null ||
        children[j] === undefined
      ) {
        el.appendChild(document.createTextNode(children[j]?.toString() || ""));
      } else {
        el.appendChild(children[j]);
      }
    }
    return el;
  };
}
